version: '3.8'

services:
  # PostgreSQL データベース（Event Store用）
  postgres:
    image: postgres:15-alpine
    container_name: cqrs-postgres
    environment:
      POSTGRES_DB: cqrs_taskmanager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cqrs_taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis（Read Model キャッシュ用）
  redis:
    image: redis:7-alpine
    container_name: cqrs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cqrs-api
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: cqrs_taskmanager
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

